version: '3.4'

volumes:
  data:

services:
  mamithonbackend:
    image: mamithonbackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
      DB_HOST: mamithonbd
      DB_PORT: 3306
      DB_USER: docker
      DB_PASSWORD: docker
      DB_NAME: mamithon
    volumes:
      - .:/usr/src/app
    links:
      - mamithonbd
    depends_on:
      - mamithonbd

  mamithonbd:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mamithon
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_NAME: mamithon
    volumes:
      - data:/var/lib/mysql
      - ./dev/mariadb:/docker-entrypoint-initdb.d
