name: node.js

on:
  [pull, pull_request]:
    branches:
      - master
      - dev

jobs:
  run-test:
    name: run node test
    runs-on: ubuntu-latest
    steps:
        - name: install dependancies
          run: npm install
        - name: run test
          run: npm test